config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  
  
  root 'task_keepers#index'
=======

>>>>>>> 79396bd2d814f6536abdba6197ab6d921fcb0c80
end

app/models/task_keeper.rb
class TaskKeeper < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/task_keepers_controller.rb
class TaskKeepersController < ApplicationController
  before_action :set_task_keeper, only: [:show, :edit, :update, :destroy]

  # GET /task_keepers
  # GET /task_keepers.json
  def index
    @task_keepers = TaskKeeper.all
  end

  # GET /task_keepers/1
  # GET /task_keepers/1.json
  def show
  end

  # GET /task_keepers/new
  def new
    @task_keeper = TaskKeeper.new
  end

  # GET /task_keepers/1/edit
  def edit
  end

  # POST /task_keepers
  # POST /task_keepers.json
  def create
    @task_keeper = TaskKeeper.new(task_keeper_params)

    respond_to do |format|
      if @task_keeper.save
        format.html { redirect_to @task_keeper, notice: 'Task keeper was successfully created.' }
        format.json { render :show, status: :created, location: @task_keeper }
      else
        format.html { render :new }
        format.json { render json: @task_keeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_keepers/1
  # PATCH/PUT /task_keepers/1.json
  def update
    respond_to do |format|
      if @task_keeper.update(task_keeper_params)
        format.html { redirect_to @task_keeper, notice: 'Task keeper was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_keeper }
      else
        format.html { render :edit }
        format.json { render json: @task_keeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_keepers/1
  # DELETE /task_keepers/1.json
  def destroy
    @task_keeper.destroy
    respond_to do |format|
      format.html { redirect_to task_keepers_url, notice: 'Task keeper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_keeper
      @task_keeper = TaskKeeper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_keeper_params
      params.require(:task_keeper).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_keepers_helper.rb
module TaskKeepersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div>
    LOGO
  </div>
</header>

<%= yield %>

</body>
</html>

app/views/task_keepers/_form.html.erb
<%= form_for(@task_keeper) do |f| %>
  <% if @task_keeper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_keeper.errors.count, "error") %> prohibited this task_keeper from being saved:</h2>

      <ul>
      <% @task_keeper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_keepers/edit.html.erb
<h1>Editing Task Keeper</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_keeper %> |
<%= link_to 'Back', task_keepers_path %>

app/views/task_keepers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jamal Task Manager</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_keepers.each do |task_keeper| %>
      <tr>
        <td><%= task_keeper.title %></td>
        <td><%= task_keeper.description %></td>
        <td><%= link_to 'Show', task_keeper %></td>
        <td><%= link_to 'Edit', edit_task_keeper_path(task_keeper) %></td>
        <td><%= link_to 'Destroy', task_keeper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/task_keepers/new.html.erb
<h1>New Task Keeper</h1>

<%= render 'form' %>

<%= link_to 'Back', task_keepers_path %>

app/views/task_keepers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jamal Task Manager</strong>
  <%= @task_keeper.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_keeper.description %>
</p>

<%= link_to 'Edit', edit_task_keeper_path(@task_keeper) %> |
<%= link_to 'Back', task_keepers_path %>